# Testing Environment Configuration
gate:
  host: "localhost"
  ports:
    http: 18080
    https: 18443
  logs:
    level: "warn"
    console: true
    file: "./log/gate-test.log"
  acme:
    directory_url: "https://acme-staging-v02.api.letsencrypt.org/directory"
    email: "test@last-emo-boy.local"
    cache_dir: "./certs-test"
    challenge_type: "http-01"
    enabled: false

console:
  host: "localhost"
  port: 18082
  logs:
    level: "warn"
    console: true
    file: "./log/console-test.log"
  database:
    path: ":memory:"  # In-memory database for testing
    wal_mode: false
    timeout: "5s"
  auth:
    jwt:
      secret: "test-secret-key-for-testing-only"
      expires_hours: 1
    session:
      timeout_minutes: 15
  cors:
    enabled: true
    origins: ["http://localhost:3001"]
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    headers: ["Content-Type", "Authorization"]

orchestrator:
  host: "localhost"
  port: 18090
  logs:
    level: "warn"
    console: true
    file: "./log/orchestrator-test.log"
  node_name: "test-node"
  cluster_mode: false
  health_check_interval: "10s"
  resource_monitoring: false
  default_replicas: 1
  max_deployments: 10
  enable_metrics: false
  workers:
    max: 2
    timeout: "10s"
  queue:
    size: 100
    timeout: "1m"

probe:
  host: "localhost"
  port: 18085
  logs:
    level: "warn"
    console: true
    file: "./log/probe-test.log"
  check_interval: "5s"
  alert_interval: "10s"
  cleanup_interval: "1h"
  result_retention: "1h"
  alert_retention: "24h"
  enable_notifications: false
  max_concurrent_probes: 5

snap:
  host: "localhost"
  port: 18086
  logs:
    level: "warn"
    console: true
    file: "./log/snap-test.log"
  repo_dir: "./test-data/snapshots"
  temp_dir: "./tmp/test-snap"
  max_parallel: 2
  rate_limit: "5MB/s"
  scrub_interval: "1h"
  default_retention:
    daily: 1
    weekly: 0
    monthly: 0
    yearly: 0